# This file generates the GitHub Actions matrix
---
include:
  # akohekohe




  # cosmo

  - board: nice_nano@2
    shield: cosmo_left rgbled_adapter
    snippet: common-config studio-rpc-usb-uart
    artifact-name: cosmo_central_left
  - board: nice_nano@2
    shield: cosmo_left rgbled_adapter
    snippet: common-config
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: cosmo_peripheral_left
  - board: nice_nano@2
    shield: cosmo_right rgbled_adapter
    snippet: common-config
    artifact-name: cosmo_peripheral_right


  - board: nice_nano@2
    shield: cosmo_left rgbled_adapter
    snippet: common-config zmk-usb-logging studio-rpc-usb-uart
    cmake-args: -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
    artifact-name: cosmo_central_left_with_logging




  # sweep

  - board: nice_nano@2
    shield: sweep_left led_indicator
    snippet: common-config studio-rpc-usb-uart
    artifact-name: sweep_central_left
  - board: nice_nano@2
    shield: sweep_left led_indicator
    snippet: common-config
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: sweep_peripheral_left
  - board: nice_nano@2
    shield: sweep_right led_indicator
    snippet: common-config
    artifact-name: sweep_peripheral_right

  - board: nice_nano@2
    shield: sweep_left led_indicator
    snippet: common-config zmk-usb-logging studio-rpc-usb-uart
    cmake-args: -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
    artifact-name: sweep_central_left_with_logging

  # reset
  - board: xiao_ble
    shield: settings_reset
  - board: nice_nano@2
    shield: settings_reset
